baseURL                    = "https://lllllyuan.github.io"
builddrafts                = false
languageCode               = "zn-Hans"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 10      #分栏文章展示数量

theme                      = "AllinOne"
title                      = "BestYuan"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"
    comment                = false    #是否 在列表页开启评论功能

  [[menu.main]]
    name                   = "Moment"
    weight                 = -110
    identifier             = "moment"
    url                    = "moment/"
    comment                = false

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"
    comment                = true

  [[menu.main]]
    name                   = "Frendly Link"
    weight                 = -100
    identifier             = "friendlylink"
    url                    = "friendlylink/"
    comment                = false



[params]
  faviconfile              = "img/liu.png"               # 博客图标 from static/
  avatar                   = "img/me.jpg"             # 头像 path to image in static dir e.g img/avatar.png
  author                   = "BestYuan"              # 博客作者
  description              = ["Be myself.", "Love the wonderful world.", "Do the right things and be a better man."]           # appears in the site header when set to a non-empty string
  welcome_head             = "Hello, World!"
  welcome_word             = "~ No Day But Today ~"

  latestpostscount         = 6                            # homepage最近文章展示数量
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting
  highlightjs              = true

  # latex
  katex                    = true

  # links
   email                    = "461192586@qq.com"
   github                   = "https://github.com/LLLLLyuan"
#   linkedin                 = "//linkedin.com/in/you"
#  facebook                 = "//facebook.com/you"
#  googleplus               = "//google.com/you"
#  twitter                  = "//twitter.com/you"
#  instagram                = "//instagram.com/you"

   include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon

  # analytics
  googleAnalytics          = "UA-149678098-1"  # 谷歌统计

  #counter
  busuanzi                 = true   # 不蒜子统计记录

# 评论
[params.utteranc]
    enable = true
    repo = "LLLLLyuan/lllllyuan.github.io"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种